source :rubygems

gem 'sinatra', '0.9.6'
gem 'thin'
gem 'haml'
gem 'sequel'
gem 'rack'
gem 'yajl-ruby'
gem 'mongo', '0.19.1'
gem 'mongo_ext', '0.19.1'
gem 'ruby2ruby'
gem 'ruby_parser'
gem 'ParseTree'
gem 'bcrypt-ruby'
gem 'rake'
