source 'http://rubygems.org'

gem 'rails', '3.0.0.beta4'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'haml'
gem 'mongo'
gem 'bcrypt-ruby'
gem "rspec-rails", ">= 2.0.0.beta.17"

gem "mongoid", ">= 2.0.0.beta9"
gem "bson_ext", "1.0.4"
